name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test, Fmt, Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --verbose

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
